// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGuildSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGuildSystem {
  error GuildSystem__CannotDemoteBelowZero(uint256 characterId);
  error GuildSystem__OnlyGuildMaster();

  function dreamin__activate(uint256 characterId) external;

  function dreamin__isMember(uint256 characterId) external view returns (bool);

  function dreamin__getMembers() external view returns (uint256[] memory);

  function dreamin__getRank(uint256 characterId) external view returns (uint256);
}
